name: Threat Model Generation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate-threat-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytm graphviz plantuml

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Generate threat model diagrams
        run: make diagrams

      - name: Check for changes
        id: git-check
        run: |
          git add sequence.png dfd.png
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "Update threat model diagrams [skip ci]"
          git push 